Added routing
reload/pet-dream-store pull request #8
Opened 2022-03-11 13:29 UTC by Adamik10

- new dependency - react-router-dom
- added new static pages: about, contact, 404

2022-03-14 09:00 UTC, spaceo commented on app/src/App.tsx
> +    <>
Why are the fragments used here? Just curious :)

2022-03-14 09:13 UTC, spaceo reviewed
Router for the win!
I have a few comments.
Mostly suggestions.

2022-03-14 09:13 UTC, spaceo commented on app/src/components/About.tsx
> +import React from "react";
I think it could make sense to make a new folder at the same level as components called pages?
And maybe to make it even more obvious we could also call the file AboutPage.tsx?

2022-03-14 09:13 UTC, spaceo commented on app/src/components/CardGrid.tsx
> +              color={`${animal.animal === "crocodile" ? "#7bb853" : "#f0cc55"}`}
I think we should put this in a map somewhere. We could make a conf/animals.ts object like:
```
export animals {
  "Crocodile": {
    color: "#....",
  },
  "Cat": {
     ...
  }
}

2022-03-14 09:13 UTC, spaceo commented on app/src/components/Contact.tsx
> +import React from "react";
See my About comment :)

2022-03-14 09:13 UTC, spaceo commented on app/src/components/Oopsie.tsx
> +import React from "react";
Well, you know :)

2022-03-14 09:19 UTC, Adamik10 commented on app/src/App.tsx
> +    <>
I added another component/div there, so I made it to a fragment, then I removed the div, but didn't remove the fragment. Reverting it now ;)

2022-03-14 09:20 UTC, Adamik10 commented on app/src/components/About.tsx
> +import React from "react";
That sounds like a great way of doing it! On it.

2022-03-14 18:39 UTC, spaceo approved these changes
There is still one thing that can be retrieved in the configuration.

2022-03-14 19:10 UTC, spaceo requested changes
The package.json problem needs to be solved as a minimum.

2022-03-14 19:10 UTC, spaceo commented on package.json
> +    "react-router-dom": "6"
Wrong file. It should be added to app/package.json

2022-03-14 19:10 UTC, spaceo commented on app/src/components/CardGrid.tsx
> +              color={`${animal.animal === "crocodile" ? "#7bb853" : "#f0cc55"}`}
I have made a suggestion to cleanup this part of the code:
https://github.com/reload/pet-dream-store/pull/9

2022-03-16 08:22 UTC, spaceo approved these changes

2022-03-16 08:22 UTC, spaceo commented
LGTM 👍

2023-11-29 07:05 UTC, closed without merging